#!/bin/bash

# Start the first process
./cache_clearer &

# Start the second process
python3 -u ./main.py &

# Wait for any process to exit
wait -n

# Exit with status of process that exited first
exit $?